package vttp.batch5.ssf.day16.models;

// record - concise (shortcut) way to create class to store data passed in
// all values are stored as final
// toString(), equals(), and hashCode() are all auto-generated by record
public record SearchParams(String query, String category, String country) {
}
